version: '2'

services:
  # elasticsearch:
  #   ports:
  #     - "9200:9200"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./elasticsearch/data/esdata1:/usr/share/elasticsearch/data
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   networks:
  #     - elk
  # kibana:
  #   ports:
  #     - "5601:5601"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   build:
  #     context: kibana/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  #   networks:
  #     - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5001:5000"
      - "9601:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - elk
    # depends_on:
    #   - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
networks:

  elk:
    driver: bridge
