---
## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-full.yml
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://115.84.183.195:9201" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: false
# xpack.monitoring.elasticsearch.username: elastic
# xpack.monitoring.elasticsearch.password: hdk
# queue.type: persisted
# queue.max_bytes: 4gb
