
# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: analyzer-comment
  path.config: "/usr/share/logstash/pipeline/analyzer-comment.conf"
- pipeline.id: smm-mobile-feed
  path.config: "/usr/share/logstash/pipeline/smm-mobile-feed.conf"
  pipeline.workers: 2
- pipeline.id: smm-mobile-comment
  path.config: "/usr/share/logstash/pipeline/smm-mobile-comment.conf"
  pipeline.workers: 2
- pipeline.id: smm-cars-feed
  path.config: "/usr/share/logstash/pipeline/smm-cars-feed.conf"
  pipeline.workers: 2
- pipeline.id: smm-cars-comment
  path.config: "/usr/share/logstash/pipeline/smm-cars-comment.conf"
  pipeline.workers: 3