- pipeline.id: smm-comment
  path.config: "/usr/share/logstash/pipeline/smm-comment.conf"
  queue.type: persisted
- pipeline.id: smm-feed
  path.config: "/usr/share/logstash/pipeline/smm-feed.conf"
  queue.type: persisted
- pipeline.id: smm-share
  path.config: "/usr/share/logstash/pipeline/smm-share.conf"
  queue.type: persisted